# Generated by Django 3.2.5 on 2022-07-09 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discordID', models.IntegerField()),
                ('discordName', models.CharField(max_length=35)),
                ('discordPFP', models.URLField()),
                ('date_verified', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_number', models.SmallIntegerField()),
                ('slug', models.CharField(max_length=200)),
                ('difficulty', models.SmallIntegerField(choices=[(0, 'Easy'), (1, 'Medium'), (2, 'Hard')])),
            ],
        ),
        migrations.CreateModel(
            name='Solve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('takeaway', models.CharField(max_length=255)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Solves', to='Data.problem')),
                ('solvee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Solves', to='Data.member')),
            ],
        ),
    ]
