# Generated by Django 3.2.5 on 2022-07-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0002_alter_member_discordid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solve',
            name='takeaway',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
