# Generated by Django 3.2.5 on 2022-07-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0003_alter_solve_takeaway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solve',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
