# Generated by Django 3.2.5 on 2022-07-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0004_alter_solve_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='discordID',
            field=models.BigIntegerField(unique=True),
        ),
    ]
