# Generated by Django 3.2.5 on 2022-07-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0005_alter_member_discordid'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='num_solutions',
            field=models.SmallIntegerField(default=0),
        ),
    ]
