# Generated by Django 3.2.5 on 2022-07-10 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0006_member_num_solutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
