# Generated by Django 3.2.5 on 2022-07-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0007_problem_problem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='premium',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
