# Generated by Django 3.2.5 on 2022-07-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0008_problem_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_number',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
